// 09-frontend-react/src/pages/Atividade04.tsx
/**
 * @file Atividade04.tsx
 * @author Cristiano
 * @date 2026
 */
import React, { useState } from 'react';
import styles from './Atividade04.module.css';

const Atividade04: React.FC = () => {
  // Estado inicial da bateria
  const [battery, setBattery] = useState<number>(50);
  
  // Constante de autonomia (km por 1% de bateria)
  const KM_PER_BATTERY = 1.2;

  /**
   * @brief Centraliza a lógica de alteração de bateria com limites de segurança.
   * Em React, a atualização do estado dispara automaticamente a re-renderização.
   */
  const handleBatteryChange = (amount: number) => {
    setBattery(prev => {
      const nextValue = prev + amount;
      // Limites de 0 a 100%
      return Math.min(Math.max(nextValue, 0), 100);
    });
  };

  // Cálculo derivado do estado
  const autonomy = (battery * KM_PER_BATTERY).toFixed(1);

  return (
    <div className={styles.container}>
      <header className={styles.header}>
        <h1>Console de Operações - SkyCargo</h1>
        <p>Sistema de Gestão de Energia e Comandos Táticos</p>
      </header>

      <main className={styles.controlCenter}>
        <div className={styles.statusPanel}>
          <div className={styles.gaugeContainer}>
            <div 
              className={styles.gaugeFill} 
              style={{ 
                width: `${battery}%`,
                backgroundColor: battery > 20 ? '#39ff14' : '#ff0055' 
              }}
            ></div>
          </div>
          <div className={styles.metrics}>
            <span className={styles.batteryText}>{battery}% Bateria</span>
            <span className={styles.rangeText}>{autonomy} km disponíveis</span>
          </div>
        </div>

        <section className={styles.actionButtons}>
          <button 
            className={styles.btnCharge} 
            onClick={() => handleBatteryChange(10)}
            title="Recarregar 10% de energia"
          >
            RECARREGAR (+)
          </button>
          
          <button 
            className={styles.btnDrain} 
            onClick={() => handleBatteryChange(-15)}
            title="Gastar 15% de energia em voo"
          >
            INICIAR VOO (-)
          </button>
        </section>

        <footer className={styles.theoryBox}>
          <h4>Nota Técnica: Eventos e Funções</h4>
          <p>
            Diferente do Vanilla JS, no React não precisamos de uma função <code>atualizarInterface()</code> que manipule o DOM manualmente. 
            Ao disparar o evento <code>onClick</code>, alteramos o <strong>Estado (State)</strong>, e o React "reage" redesenhando apenas o que mudou com máxima eficiência.
          </p>
        </footer>
      </main>
    </div>
  );
};

export default Atividade04;

/* @section ArchitectureMap
 * Descrição técnica da estrutura e fluxo de dados.
 */

/*
 * RESUMO TEÓRICO
 * Alinhado com o Padrão de Entrega de Elite (Protocolo GEMINI).
 */

// 13-frontend-angular/src/app/pages/atividade04/atividade04.component.ts
import { Component, signal, computed } from '@angular/core';

/**
 * @file atividade04.component.ts
 * @brief Componente da Atividade 04: Controle e Reação (Eventos e Funções).
 * @author Gemini CLI Elite
 * @date 2026-04-30
 * 
 * @description Desafio Integrador do Nível 01. Demonstração de funções,
 * tratamento de eventos (click) e reatividade de estado via Signals.
 */

@Component({
  selector: 'app-atividade04',
  standalone: true,
  templateUrl: './atividade04.component.html',
  styleUrl: './atividade04.component.css'
})
export class Atividade04Component {
  /**
   * @description Estado atômico da bateria utilizando Signal.
   */
  protected readonly battery = signal<number>(50);

  /**
   * @description Constante de autonomia: 1.2 km por 1% de carga.
   */
  private readonly KM_PER_BATTERY = 1.2;

  /**
   * @description Cálculo reativo derivado da bateria.
   */
  protected readonly autonomy = computed(() => 
    (this.battery() * this.KM_PER_BATTERY).toFixed(1)
  );

  /**
   * @description Verifica se a bateria está em nível de alerta.
   */
  protected readonly isLowBattery = computed(() => this.battery() <= 20);

  /**
   * @brief Centraliza a alteração de energia com travas de segurança.
   * @param amount Quantidade a ser somada ou subtraída.
   */
  protected handleEnergyChange(amount: number): void {
    this.battery.update(current => {
      const nextValue = current + amount;
      // Clamping: Garante limites entre 0 e 100
      return Math.min(Math.max(nextValue, 0), 100);
    });
  }
}

/* @section ArchitectureMap
 * Descrição técnica da estrutura e fluxo de dados.
 */

/*
 * RESUMO TEÓRICO
 * Alinhado com o Padrão de Entrega de Elite (Protocolo GEMINI).
 */

<div class="container">
  <header class="header">
    <h1>Console de Missão - Nexus Angular</h1>
    <p>Gestão de Ativos e Comandos de Voo</p>
  </header>

  <main class="console-box">
    <div class="monitor-panel">
      <div class="progress-container">
        <div 
          class="progress-bar" 
          [style.width.%]="battery()"
          [class.low-power]="isLowBattery()"
        ></div>
      </div>
      
      <div class="data-grid">
        <div class="data-item">
          <span class="label">BATERIA:</span>
          <span class="value" [class.text-alert]="isLowBattery()">{{ battery() }}%</span>
        </div>
        <div class="data-item">
          <span class="label">AUTONOMIA:</span>
          <span class="value">{{ autonomy() }} km</span>
        </div>
      </div>

      @if (isLowBattery()) {
        <div class="system-alert">
          ⚠ ALERTA: Nível de energia crítico. Proceder para recarga.
        </div>
      }
    </div>

    <section class="action-grid">
      <button 
        class="btn btn-primary" 
        (click)="handleEnergyChange(10)"
        aria-label="Aumentar carga em 10%"
      >
        RECARREGAR (+)
      </button>

      <button 
        class="btn btn-danger" 
        (click)="handleEnergyChange(-15)"
        aria-label="Simular consumo de voo de 15%"
      >
        INICIAR VOO (-)
      </button>
    </section>

    <footer class="theory-note">
      <h4>Reflexão Técnica: Reatividade Industrial</h4>
      <p>
        No Angular v21, substituímos o <code>onclick</code> manual pela vinculação de evento <code>(click)</code>. 
        O uso de <strong>Signals</strong> garante que o framework redesenhe apenas os nós do DOM que dependem da bateria, 
        eliminando ciclos de detecção de mudanças globais e pesados.
      </p>
    </footer>
  </main>
</div>
