// 09-frontend-react/src/pages/Atividade03.tsx
/**
 * @file Atividade03.tsx
 * @brief Implementação/Componente Atividade03.tsx
 * @author Cristiano
 * @date 2026
 */
import React, { useState, useMemo } from 'react';
import styles from './Atividade03.module.css';

const Atividade03: React.FC = () => {
  // Estado para simular a bateria do drone
  const [battery, setBattery] = useState<number>(85);
  
  // Constante de autonomia (Requisito: Bateria * 1.5 km)
  const rangeMultiplier = 1.5;
  
  // Cálculo de Autonomia (Memoizado para performance, embora simples aqui)
  const range = useMemo(() => (battery * rangeMultiplier).toFixed(2), [battery]);

  return (
    <div className={styles.container}>
      <header className={styles.header}>
        <h1>Monitor de Autonomia - Nexus v4.0</h1>
        <p>Análise de Performance Geométrica e Energética</p>
      </header>

      <main className={styles.mainContent}>
        <section className={styles.droneCard}>
          <div className={styles.imageContainer}>
            <img 
              src="https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=600&q=80" 
              alt="Drone de Carga Industrial" 
              className={styles.droneImage}
            />
          </div>
          
          <div className={styles.infoArea}>
            <h3>Drone SkyCargo Stealth</h3>
            <div className={styles.statRow}>
              <label>Bateria Atual:</label>
              <input 
                type="range" 
                min="0" 
                max="100" 
                value={battery} 
                onChange={(e) => setBattery(Number(e.target.value))}
                className={styles.slider}
              />
              <span className={styles.statValue}>{battery}%</span>
            </div>
            
            <div className={styles.resultBox}>
              <p>Autonomia Estimada:</p>
              <span className={styles.rangeValue}>{range} km</span>
            </div>
          </div>
        </section>

        <section className={styles.theoryNote}>
          <h4>Nota Técnica: Box Model & Matemática</h4>
          <p>O card acima utiliza o <strong>CSS Box Model</strong> para garantir que a imagem e os dados não colapsem. O cálculo de autonomia é reativo: qualquer mudança no estado da bateria atualiza instantaneamente a distância operacional.</p>
        </section>
      </main>
    </div>
  );
};

export default Atividade03;

/* @section ArchitectureMap
 * Descrição técnica da estrutura e fluxo de dados.
 */

/*
 * RESUMO TEÓRICO
 * Alinhado com o Padrão de Entrega de Elite (Protocolo GEMINI).
 */

// 13-frontend-angular/src/app/pages/atividade03/atividade03.component.ts
import { Component, signal, computed } from '@angular/core';
import { FormsModule } from '@angular/forms';

/**
 * @file atividade03.component.ts
 * @brief Componente da Atividade 03: Geometria e Lógica.
 * @author Gemini CLI Elite
 * @date 2026-04-30
 * 
 * @description Demonstração de Box Model, cálculos matemáticos reativos
 * utilizando Signals e `computed` do Angular v21.
 */

@Component({
  selector: 'app-atividade03',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './atividade03.component.html',
  styleUrl: './atividade03.component.css'
})
export class Atividade03Component {
  /**
   * @description Estado reativo da bateria (0-100%).
   */
  protected readonly battery = signal<number>(85);

  /**
   * @description Constante de autonomia (Requisito: Bateria * 1.5 km).
   */
  private readonly rangeMultiplier = 1.5;

  /**
   * @description Sinal computado que deriva a autonomia da bateria.
   * Reage automaticamente às mudanças no sinal `battery`.
   */
  protected readonly range = computed(() => 
    (this.battery() * this.rangeMultiplier).toFixed(2)
  );

  /**
   * @description Atualiza o estado da bateria a partir do input do usuário.
   */
  protected onBatteryChange(event: Event): void {
    const input = event.target as HTMLInputElement;
    this.battery.set(Number(input.value));
  }
}

/* @section ArchitectureMap
 * Descrição técnica da estrutura e fluxo de dados.
 */

/*
 * RESUMO TEÓRICO
 * Alinhado com o Padrão de Entrega de Elite (Protocolo GEMINI).
 */

<div class="container">
  <header class="header">
    <h1>Monitor de Autonomia - Nexus Angular</h1>
    <p>Análise de Performance Energética via Signals</p>
  </header>

  <main class="main-content">
    <section class="drone-card">
      <div class="image-container">
        <img 
          src="https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=600&q=80" 
          alt="Drone de Carga Industrial" 
          class="drone-image"
        />
      </div>
      
      <div class="info-area">
        <h3>Drone SkyCargo Stealth</h3>
        <div class="stat-row">
          <label for="battery-slider">Bateria Atual:</label>
          <input 
            id="battery-slider"
            type="range" 
            min="0" 
            max="100" 
            [value]="battery()" 
            (input)="onBatteryChange($event)"
            class="slider"
          />
          <span class="stat-value">{{ battery() }}%</span>
        </div>
        
        <div class="result-box">
          <p>Autonomia Estimada:</p>
          <span class="range-value">{{ range() }} km</span>
        </div>
      </div>
    </section>

    <section class="theory-note">
      <h4>Nota Técnica: Box Model & Computação Reativa</h4>
      <p>O card acima utiliza o <strong>CSS Box Model</strong> (Padding, Border, Margin) para estruturação visual. A autonomia é calculada via <code>computed()</code>, uma primitiva de elite do Angular v21 que deriva novos estados com performance otimizada.</p>
    </section>
  </main>
</div>
