// 09-frontend-react/src/pages/Atividade09.tsx
/**
 * @file Atividade09.tsx
 * @author Cristiano
 * @date 2026
 */
import React, { useState, useEffect, useRef } from 'react';
import styles from './Atividade09.module.css';

/**
 * @brief Componente de Alerta (Modularizado)
 * Demonstra o uso da tag nativa <dialog> e refs em React.
 */
interface AlertModalProps {
  isOpen: boolean;
  onClose: () => void;
  message: string;
}

const AlertModal: React.FC<AlertModalProps> = ({ isOpen, onClose, message }) => {
  const dialogRef = useRef<HTMLDialogElement>(null);

  useEffect(() => {
    if (isOpen) {
      dialogRef.current?.showModal();
    } else {
      dialogRef.current?.close();
    }
  }, [isOpen]);

  return (
    <dialog 
      ref={dialogRef} 
      className={styles.modal}
      onCancel={onClose} // Trata a tecla ESC nativamente
    >
      <div className={styles.modalContent}>
        <h2>🚨 ALERTA DE EMERGÊNCIA</h2>
        <p>{message}</p>
        <div className={styles.modalActions}>
          <button onClick={onClose} className={styles.btnConfirm}>CONFIRMAR CIÊNCIA [ESC]</button>
        </div>
      </div>
    </dialog>
  );
};

const Atividade09: React.FC = () => {
  const [isAlertOpen, setIsAlertOpen] = useState(false);
  const [logMessages, setLogMessages] = useState<string[]>(["Sistema inicializado..."]);

  /**
   * @section Eventos de Teclado (Requisito de Elite)
   */
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      // Tecla 'A' para abrir alerta
      if (e.key.toLowerCase() === 'a') {
        setIsAlertOpen(true);
      }
      // Tecla 'L' para gerar log rápido
      if (e.key.toLowerCase() === 'l') {
        setLogMessages(prev => [`[${new Date().toLocaleTimeString()}] Log de campo disparado via atalho.`, ...prev]);
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  return (
    <div className={styles.container}>
      <header className={styles.header}>
        <h1>Console de Missão - Controle de Camadas</h1>
        <p>Atalhos: [A] Alerta | [L] Log Rápido | [ESC] Fechar</p>
      </header>

      <main className={styles.main}>
        <div className={styles.workspace}>
          <div className={styles.baseLayer}>
            <h3>MAPA TÁTICO (CAMADA BASE)</h3>
            <div className={styles.mapPlaceholder}>
              <div className={styles.droneMarker}>DR-09</div>
            </div>
          </div>

          {/* Botão Fixo (Requisito de Elite) */}
          <button 
            className={styles.floatingBtn}
            onClick={() => setIsAlertOpen(true)}
          >
            DISPARAR ALERTA
          </button>
        </div>

        <section className={styles.logPanel}>
          <h3>LOG DE OPERAÇÕES</h3>
          <ul>
            {logMessages.map((msg, i) => <li key={i}>{msg}</li>)}
          </ul>
        </section>
      </main>

      <AlertModal 
        isOpen={isAlertOpen} 
        onClose={() => setIsAlertOpen(false)}
        message="Risco de colisão detectado no setor 7G! Manobra evasiva recomendada."
      />

      <footer className={styles.theoryBox}>
        <h4>Nota Técnica: Camadas, Atalhos e Ref</h4>
        <p>
          Esta atividade introduz a manipulação de camadas via <strong>Z-index</strong> e <strong>position: fixed</strong>. 
          Utilizamos o hook <code>useRef</code> para interagir diretamente com a API nativa da tag <code>&lt;dialog&gt;</code>, 
          permitindo que o React controle elementos que possuem comportamento imperativo no navegador. 
          O uso de <code>window.addEventListener</code> no useEffect garante que o sistema reaja globalmente a comandos de teclado.
        </p>
      </footer>
    </div>
  );
};

export default Atividade09;

/* @section ArchitectureMap
 * Descrição técnica da estrutura e fluxo de dados.
 */

/*
 * RESUMO TEÓRICO
 * Alinhado com o Padrão de Entrega de Elite (Protocolo GEMINI).
 */

// 13-frontend-angular/src/app/pages/atividade09/atividade09.component.ts
/**
 * @date 2026
 */
import { Component, HostListener, signal } from '@angular/core';
import { AlertModalComponent } from './components/alert-modal/alert-modal.component';

/**
 * @file atividade09.component.ts
 * @brief Componente da Atividade 09: Camadas e Atalhos.
 * @author Gemini CLI Elite
 * 
 * @description Demonstração de posicionamento CSS avançado, gestão de camadas (Z-index),
 * captura de eventos globais de teclado e comunicação bidirecional entre componentes.
 */

@Component({
  selector: 'app-atividade09',
  standalone: true,
  imports: [AlertModalComponent],
  templateUrl: './atividade09.component.html',
  styleUrl: './atividade09.component.css'
})
export class Atividade09Component {
  /**
   * @description Controle de estado da modal de alerta.
   */
  protected readonly isAlertOpen = signal<boolean>(false);

  /**
   * @description Histórico de logs operacionais.
   */
  protected readonly logs = signal<string[]>(['Sistema de Camadas Nexus v1.0 ONLINE.']);

  /**
   * @brief Atalhos de Teclado Industriais (Requisito de Elite).
   * Captura teclas globalmente no contexto do componente.
   */
  @HostListener('window:keydown', ['$event'])
  handleKeyDown(event: KeyboardEvent): void {
    const key = event.key.toLowerCase();

    // [A] para Alerta
    if (key === 'a') {
      this.isAlertOpen.set(true);
    }
    
    // [L] para Log Rápido
    if (key === 'l') {
      this.addLog('Log de campo disparado via atalho [L].');
    }

    // [ESC] para fechar é tratado nativamente pelo <dialog> e emitido pelo modal
  }

  protected addLog(message: string): void {
    const timestamp = new Date().toLocaleTimeString();
    this.logs.update(current => [`[${timestamp}] ${message}`, ...current]);
  }

  protected toggleAlert(state: boolean): void {
    this.isAlertOpen.set(state);
    if (!state) {
      this.addLog('Alerta de emergência reconhecido pelo operador.');
    }
  }
}

/* @section ArchitectureMap
 * Descrição técnica da estrutura e fluxo de dados.
 */

/*
 * RESUMO TEÓRICO
 * Alinhado com o Padrão de Entrega de Elite (Protocolo GEMINI).
 */

<div class="container">
  <header class="header">
    <h1>Console de Missão - Camadas e Atalhos</h1>
    <div class="shortcut-legend">
      <span>[A] Novo Alerta</span>
      <span>[L] Log Rápido</span>
      <span>[ESC] Confirmar</span>
    </div>
  </header>

  <main class="workspace">
    <!-- Camada Base: Mapa Tático -->
    <section class="base-layer">
      <h3>MAPA TÁTICO (CAMADA Z: 0)</h3>
      <div class="map-placeholder">
        <div class="drone-marker">DR-09</div>
        <div class="grid-line"></div>
        <div class="grid-line horizontal"></div>
      </div>
    </section>

    <!-- Camada de Registro: Painel Lateral -->
    <section class="log-panel">
      <h3>LOG DE OPERAÇÕES</h3>
      <ul class="log-list">
        @for (log of logs(); track $index) {
          <li>{{ log }}</li>
        }
      </ul>
    </section>

    <!-- Botão Flutuante (Requisito de Elite: position: fixed) -->
    <button 
      class="floating-btn"
      (click)="toggleAlert(true)"
      title="Disparar Alerta Manual [A]"
    >
      🚨
    </button>
  </main>

  <!-- Componente Modal (Camada Z: Topo) -->
  <app-alert-modal 
    [isOpen]="isAlertOpen()"
    [message]="'Risco de colisão iminente no Setor 7G! Execute manobra evasiva agora.'"
    (close)="toggleAlert(false)"
  />

  <footer class="theory-box">
    <h4>Reflexão Técnica: Camadas, Atalhos e Comunicação</h4>
    <p>
      Nesta atividade, exploramos o <strong>Z-index</strong> e o posicionamento <strong>fixed/absolute</strong> para organizar a hierarquia visual. 
      A comunicação entre o Console e a Modal ocorre via <code>[isOpen]</code> (Input) e <code>(close)</code> (Output). 
      O uso do <code>&#64;HostListener</code> permite que o sistema reaja a comandos de hardware (teclado), 
      uma característica essencial de interfaces industriais de alto desempenho.
    </p>
  </footer>
</div>
