// 13-frontend-angular/src/app/app.ts
/**
 * @file app.ts
 * @brief Implementação/Componente app.ts
 * @author Cristiano
 * @date 2026
 */
import { Component, signal } from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet],
  templateUrl: './app.html',
  styleUrl: './app.css'
})
export class App {
  protected readonly title = signal('13-frontend-angular');
}

/* @section ArchitectureMap
 * Descrição técnica da estrutura e fluxo de dados.
 */

/*
 * RESUMO TEÓRICO
 * Alinhado com o Padrão de Entrega de Elite (Protocolo GEMINI).
 */

// 07-frontend-mastery/desafios-sa/SA-02-skycargo-react/src/App.tsx
/**
 * @author Cristiano
 * @date 2026
 */
/**
 * @file App.tsx
 * @brief Orquestrador Final do SkyCargo React Engine (SA-02).
 */

import './styles/theme.css';
import { MissionProvider } from './contexts/MissionContext';
import ControlTower from './components/ControlTower';

function App() {
  return (
    <MissionProvider>
        <ControlTower />
    </MissionProvider>
  );
}

export default App;

/* @section ArchitectureMap
 * Descrição técnica da estrutura e fluxo de dados.
 */

/*
 * RESUMO TEÓRICO
 * Alinhado com o Padrão de Entrega de Elite (Protocolo GEMINI).
 */
