// 13-frontend-angular/src/app/pages/atividade06/atividade06.component.ts
import { Component, signal } from '@angular/core';

/**
 * @file atividade06.component.ts
 * @brief Componente da Atividade 06: A Frota em Massa.
 * @author Gemini CLI Elite
 * @date 2026-04-30
 * 
 * @description Demonstração de Arrays, tabelas industriais e renderização dinâmica
 * utilizando a nova Control Flow Syntax (@for) e Signals do Angular v21.
 */

interface Drone {
  id: string;
  model: string;
  battery: number;
  status: 'READY' | 'FLYING' | 'MAINTENANCE';
}

@Component({
  selector: 'app-atividade06',
  standalone: true,
  templateUrl: './atividade06.component.html',
  styleUrl: './atividade06.component.css'
})
export class Atividade06Component {
  /**
   * @description Lista de frota gerenciada via Signal reativo.
   */
  protected readonly fleet = signal<Drone[]>([
    { id: 'S-001', model: 'Interceptor', battery: 95, status: 'READY' },
    { id: 'S-002', model: 'Cargo Hauler', battery: 40, status: 'FLYING' },
    { id: 'S-003', model: 'Explorer v2', battery: 15, status: 'MAINTENANCE' },
  ]);

  /**
   * @brief Simula a adição de uma nova unidade à frota.
   */
  protected addUnit(): void {
    const nextId = this.fleet().length + 1;
    const newDrone: Drone = {
      id: `S-00${nextId}`,
      model: 'Standard Unit',
      battery: 100,
      status: 'READY'
    };

    // Imutabilidade via Signal Update
    this.fleet.update(current => [...current, newDrone]);
  }
}

/* @section ArchitectureMap
 * Descrição técnica da estrutura e fluxo de dados.
 */

/*
 * RESUMO TEÓRICO
 * Alinhado com o Padrão de Entrega de Elite (Protocolo GEMINI).
 */

<div class="container">
  <header class="header">
    <h1>Frota Global - Nexus Angular</h1>
    <p>Monitoramento de Unidades em Massa (Nível 06)</p>
  </header>

  <main class="main-content">
    <div class="action-bar">
      <button (click)="addUnit()" class="btn-add">ADICIONAR UNIDADE (+)</button>
      <span class="fleet-info">Total de Ativos: <strong>{{ fleet().length }}</strong></span>
    </div>

    <section class="table-container">
      <table class="nexus-table">
        <thead>
          <tr>
            <th>ID</th>
            <th>MODELO</th>
            <th>BATERIA</th>
            <th>STATUS</th>
          </tr>
        </thead>
        <tbody>
          @for (drone of fleet(); track drone.id) {
            <tr class="drone-row">
              <td class="id-cell">{{ drone.id }}</td>
              <td>{{ drone.model }}</td>
              <td>
                <div class="battery-display">
                  <div class="battery-track">
                    <div 
                      class="battery-fill" 
                      [style.width.%]="drone.battery"
                      [class.critical]="drone.battery < 20"
                    ></div>
                  </div>
                  <span class="percentage">{{ drone.battery }}%</span>
                </div>
              </td>
              <td>
                <span class="status-badge" [attr.data-status]="drone.status">
                  {{ drone.status }}
                </span>
              </td>
            </tr>
          } @empty {
            <tr>
              <td colspan="4" class="empty-msg">Nenhuma unidade detectada no radar.</td>
            </tr>
          }
        </tbody>
      </table>
    </section>

    <footer class="theory-box">
      <h3>Diferencial Técnico: &#64;for vs *ngFor</h3>
      <p>
        No Angular v21, abandonamos a diretiva <code>*ngFor</code>. O novo bloco <code>&#64;for</code> é integrado ao compilador, não exige NgModules e possui uma performance de rastreamento (<code>track</code>) nativa muito superior, além de permitir o bloco <code>&#64;empty</code> para estados vazios sem lógica extra.
      </p>
    </footer>
  </main>
</div>

// 09-frontend-react/src/pages/Atividade06.tsx
/**
 * @file Atividade06.tsx
 * @brief Implementação/Componente Atividade06.tsx
 * @author Cristiano
 * @date 2026
 */
import React, { useState } from 'react';
import styles from './Atividade06.module.css';

interface Drone {
  id: string;
  model: string;
  battery: number;
  status: 'READY' | 'FLYING' | 'MAINTENANCE';
}

const Atividade06: React.FC = () => {
  // Estado inicial da Frota (Array de Objetos)
  const [fleet, setFleet] = useState<Drone[]>([
    { id: "S-001", model: "Interceptor", battery: 95, status: 'READY' },
    { id: "S-002", model: "Cargo Hauler", battery: 40, status: 'FLYING' },
    { id: "S-003", model: "Explorer v2", battery: 15, status: 'MAINTENANCE' },
  ]);

  // Função para simular atualização de frota (Adicionar novo drone)
  const addDrone = () => {
    const newId = `S-00${fleet.length + 1}`;
    const newDrone: Drone = {
      id: newId,
      model: "Standard Unit",
      battery: 100,
      status: 'READY'
    };
    setFleet([...fleet, newDrone]);
  };

  return (
    <div className={styles.container}>
      <header className={styles.header}>
        <h1>Central de Monitoramento Global</h1>
        <p>Controle de Frota LogiSpeed - Nível 06</p>
      </header>

      <main className={styles.main}>
        <div className={styles.actionBar}>
          <button onClick={addDrone} className={styles.btnAdd}>ADICIONAR UNIDADE (+)</button>
          <span className={styles.fleetCount}>Total de Unidades: {fleet.length}</span>
        </div>

        <section className={styles.tableContainer}>
          <table className={styles.fleetTable}>
            <thead>
              <tr>
                <th>ID</th>
                <th>MODELO</th>
                <th>BATERIA</th>
                <th>STATUS OPERACIONAL</th>
              </tr>
            </thead>
            <tbody>
              {fleet.map((drone) => (
                <tr key={drone.id} className={styles.droneRow}>
                  <td className={styles.idCell}>{drone.id}</td>
                  <td>{drone.model}</td>
                  <td>
                    <div className={styles.batteryCell}>
                      <div className={styles.batteryMinibar}>
                        <div 
                          className={styles.fill} 
                          style={{ 
                            width: `${drone.battery}%`,
                            backgroundColor: drone.battery < 20 ? '#ff0055' : '#39ff14'
                          }}
                        ></div>
                      </div>
                      <span>{drone.battery}%</span>
                    </div>
                  </td>
                  <td className={`${styles.statusCell} ${styles[drone.status]}`}>
                    {drone.status}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          {/* Refatoração Semântica: React map em tabelas deve retornar <tr> diretamente para manter a estrutura */}
        </section>

        <footer className={styles.theoryBox}>
          <h4>Nota Técnica: Arrays & Renderização Dinâmica</h4>
          <p>
            No React, não usamos <code>forEach</code> para manipular o DOM manualmente. 
            Utilizamos o método <code>.map()</code> para transformar cada objeto do array <strong>fleet</strong> em uma linha da tabela (JSX). 
            A "Key" é fundamental para que o React saiba qual item atualizar sem redesenhar a frota inteira.
          </p>
        </footer>
      </main>
    </div>
  );
};

export default Atividade06;

/* @section ArchitectureMap
 * Descrição técnica da estrutura e fluxo de dados.
 */

/*
 * RESUMO TEÓRICO
 * Alinhado com o Padrão de Entrega de Elite (Protocolo GEMINI).
 */
