// 13-frontend-angular/src/app/pages/atividade02/atividade02.component.ts
import { Component, signal } from '@angular/core';

/**
 * @file atividade02.component.ts
 * @brief Componente da Atividade 02: O Inventário Digital.
 * @author Gemini CLI Elite
 * @date 2026-04-30
 *
 * @description Demonstração de listas, variáveis tipadas e reatividade fina
 * utilizando Signals e a nova Control Flow Syntax do Angular v21.
 */

interface Drone {
  id: string;
  name: string;
  status: 'active' | 'warning';
}

@Component({
  selector: 'app-atividade02',
  standalone: true,
  templateUrl: './atividade02.component.html',
  styleUrl: './atividade02.component.css'
})
export class Atividade02Component {
  /**
   * @description Constantes e Signals (JS Atitude)
   */
  protected readonly systemVersion = 'v3.0.0-angular';
  protected readonly operatorName = signal('Cristiano');

  /**
   * @description Lista de drones gerenciada via Signal reativo.
   */
  protected readonly drones = signal<Drone[]>([
    { id: 'D-001', name: 'SkyHawk Zero', status: 'active' },
    { id: 'D-002', name: 'StormRunner', status: 'warning' },
    { id: 'D-003', name: 'ThunderBolt', status: 'active' },
  ]);
}

/* @section ArchitectureMap
 * Descrição técnica da estrutura e fluxo de dados.
 */

/*
 * RESUMO TEÓRICO
 * Alinhado com o Padrão de Entrega de Elite (Protocolo GEMINI).
 */

<div class="container">
  <header class="header">
    <h1>Inventário de Frota - Nexus Angular</h1>
    <p>Operador: <strong>{{ operatorName() }}</strong> | Versão: {{ systemVersion }}</p>
  </header>

  <section class="inventory">
    <h2>Status dos Drones em Tempo Real</h2>
    <ul class="drone-list">
      @for (drone of drones(); track drone.id) {
        <li 
          [class.active]="drone.status === 'active'"
          [class.warning]="drone.status === 'warning'"
          [id]="drone.status === 'warning' ? 'drone-warning' : ''"
          class="drone-item"
        >
          <span class="drone-id">[{{ drone.id }}]</span>
          <span class="drone-name">{{ drone.name }}</span>
          <span class="status-badge">
            {{ drone.status === 'active' ? '● OPERACIONAL' : '▲ FALHA DE SISTEMA' }}
          </span>
        </li>
      }
    </ul>
  </section>
</div>

// 09-frontend-react/src/pages/Atividade02.tsx
/**
 * @file Atividade02.tsx
 * @brief Implementação/Componente Atividade02.tsx
 * @author Cristiano
 * @date 2026
 */
import React, { useState } from 'react';
import styles from './Atividade02.module.css';

interface Drone {
  id: string;
  name: string;
  status: 'active' | 'warning';
}

const Atividade02: React.FC = () => {
  // JS (Atitude): Declarando constantes e estados
  const systemVersion = "v2.0.0-react";
  const [operatorName] = useState<string>("Cristiano");

  const drones: Drone[] = [
    { id: "D-001", name: "SkyHawk Zero", status: 'active' },
    { id: "D-002", name: "StormRunner", status: 'warning' },
    { id: "D-003", name: "ThunderBolt", status: 'active' },
  ];

  return (
    <div className={styles.container}>
      <header className={styles.header}>
        <h1>Inventário de Frota - Nexus React</h1>
        <p>Operador: <strong>{operatorName}</strong> | Versão: {systemVersion}</p>
      </header>

      <section className={styles.inventory}>
        <h2>Status dos Drones em Tempo Real</h2>
        <ul className={styles.droneList}>
          {drones.map((drone) => (
            <li 
              key={drone.id} 
              className={`${styles.droneItem} ${drone.status === 'warning' ? styles.warning : styles.active}`}
              id={drone.status === 'warning' ? 'drone-warning' : undefined}
            >
              <span className={styles.droneId}>[{drone.id}]</span>
              <span className={styles.droneName}>{drone.name}</span>
              <span className={styles.statusBadge}>
                {drone.status === 'active' ? '● OPERACIONAL' : '▲ FALHA DE SISTEMA'}
              </span>
            </li>
          ))}
        </ul>
      </section>
    </div>
  );
};

export default Atividade02;

/* @section ArchitectureMap
 * Descrição técnica da estrutura e fluxo de dados.
 */

/*
 * RESUMO TEÓRICO
 * Alinhado com o Padrão de Entrega de Elite (Protocolo GEMINI).
 */
