// 13-frontend-angular/src/app/pages/atividade05/atividade05.component.ts
import { Component, signal, computed } from '@angular/core';
import { FormsModule } from '@angular/forms';

/**
 * @file atividade05.component.ts
 * @brief Componente da Atividade 05: Inteligência e Flexibilidade.
 * @author Gemini CLI Elite
 * @date 2026-04-30
 * 
 * @description Demonstração de formulários, Flexbox e lógica condicional reativa
 * utilizando Signals e a nova Control Flow Syntax do Angular v21.
 */

@Component({
  selector: 'app-atividade05',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './atividade05.component.html',
  styleUrl: './atividade05.component.css'
})
export class Atividade05Component {
  /**
   * @description Estados reativos via Signals.
   */
  protected readonly callsign = signal<string>('SKY-RAPTOR');
  protected readonly tempCallsign = signal<string>('');
  protected readonly battery = signal<number>(100);

  /**
   * @description Lógica Condicional Computada (Requisito de Elite).
   */
  protected readonly isCritical = computed(() => this.battery() < 20);

  /**
   * @brief Atualiza o registro oficial do drone (Callsign).
   */
  protected updateCallsign(): void {
    if (this.tempCallsign().trim()) {
      this.callsign.set(this.tempCallsign().toUpperCase());
      this.tempCallsign.set('');
    }
  }

  /**
   * @brief Gerenciamento de Carga com limites de segurança.
   */
  protected modifyBattery(amount: number): void {
    this.battery.update(current => {
      const next = current + amount;
      return Math.min(Math.max(next, 0), 100);
    });
  }

  /**
   * @brief Handler para o input de texto do formulário.
   */
  protected onInputChange(event: Event): void {
    const input = event.target as HTMLInputElement;
    this.tempCallsign.set(input.value);
  }
}

/* @section ArchitectureMap
 * Descrição técnica da estrutura e fluxo de dados.
 */

/*
 * RESUMO TEÓRICO
 * Alinhado com o Padrão de Entrega de Elite (Protocolo GEMINI).
 */

<div class="container" [class.perigo]="isCritical()" [class.normal]="!isCritical()">
  <header class="header">
    <h1>Nexus Control v5.0 - {{ callsign() }}</h1>
    <div class="status-badge">
      @if (isCritical()) {
        ⚠️ STATUS: ALERTA CRÍTICO
      } @else {
        ✅ STATUS: OPERAÇÃO NORMAL
      }
    </div>
  </header>

  <main class="dashboard">
    <!-- Seção de Configuração (Formulários) -->
    <section class="config-panel">
      <h2><span class="icon">⚙️</span> Configuração de Unidade</h2>
      <form (submit)="updateCallsign(); $event.preventDefault()" class="form">
        <div class="input-group">
          <label for="callsign-input">Novo Callsign:</label>
          <input 
            id="callsign-input"
            type="text" 
            placeholder="Ex: ALPHA-01"
            [value]="tempCallsign()"
            (input)="onInputChange($event)"
          />
        </div>
        <button type="submit" class="btn-action">ATUALIZAR REGISTRO</button>
      </form>
    </section>

    <!-- Seção de Telemetria (Flexbox) -->
    <section class="telemetry-panel">
      <h2><span class="icon">🔋</span> Gestão de Energia</h2>
      <div class="energy-control">
        <button (click)="modifyBattery(-10)">REDUZIR CARGA</button>
        <div class="battery-value">{{ battery() }}%</div>
        <button (click)="modifyBattery(10)">REABASTECER</button>
      </div>
      <div class="progress-bar">
        <div class="progress-fill" [style.width.%]="battery()"></div>
      </div>
    </section>
  </main>

  <footer class="theory-box">
    <h3>Resumo Técnico: Inteligência & Layout Flexível</h3>
    <p>
      Este componente demonstra a integração de <strong>Flexbox</strong> para layouts adaptáveis e 
      <strong>Signals</strong> para lógica condicional. Através do <code>computed()</code>, detectamos estados críticos e injetamos classes CSS dinamicamente, permitindo que a interface reaja em tempo real à realidade dos dados.
    </p>
  </footer>
</div>

// 09-frontend-react/src/pages/Atividade05.tsx
/**
 * @file Atividade05.tsx
 * @brief Implementação/Componente Atividade05.tsx
 * @author Cristiano
 * @date 2026
 */
import React, { useState } from 'react';
import styles from './Atividade05.module.css';

const Atividade05: React.FC = () => {
  // Estados para gerenciar o formulário e telemetria
  const [callsign, setCallsign] = useState<string>("SKY-RAPTOR");
  const [tempCallsign, setTempCallsign] = useState<string>("");
  const [battery, setBattery] = useState<number>(100);

  // Lógica Condicional (Requisito de Elite)
  const isCritical = battery < 20;
  
  const handleUpdateCallsign = (e: React.FormEvent) => {
    e.preventDefault();
    if (tempCallsign.trim()) {
      setCallsign(tempCallsign.toUpperCase());
      setTempCallsign("");
    }
  };

  return (
    <div className={`${styles.container} ${isCritical ? styles.perigo : styles.normal}`}>
      <header className={styles.header}>
        <h1>Nexus Control v5.0 - {callsign}</h1>
        <div className={styles.statusBadge}>
          {isCritical ? "⚠️ STATUS: ALERTA CRÍTICO" : "✅ STATUS: OPERAÇÃO NORMAL"}
        </div>
      </header>

      <main className={styles.dashboard}>
        {/* Seção de Configuração (Formulários) */}
        <section className={styles.configPanel}>
          <h2><span className={styles.icon}>⚙️</span> Configuração de Unidade</h2>
          <form onSubmit={handleUpdateCallsign} className={styles.form}>
            <div className={styles.inputGroup}>
              <label htmlFor="callsign-input">Novo Callsign:</label>
              <input 
                id="callsign-input"
                type="text" 
                placeholder="Ex: ALPHA-01"
                value={tempCallsign}
                onChange={(e) => setTempCallsign(e.target.value)}
              />
            </div>
            <button type="submit" className={styles.btnAction}>ATUALIZAR REGISTRO</button>
          </form>
        </section>

        {/* Seção de Telemetria (Flexbox) */}
        <section className={styles.telemetryPanel}>
          <h2><span className={styles.icon}>🔋</span> Gestão de Energia</h2>
          <div className={styles.energyControl}>
            <button onClick={() => setBattery(prev => Math.max(0, prev - 10))}>REDUZIR CARGA</button>
            <div className={styles.batteryValue}>{battery}%</div>
            <button onClick={() => setBattery(prev => Math.min(100, prev + 10))}>REABASTECER</button>
          </div>
          <div className={styles.progressBar}>
            <div className={styles.progressFill} style={{ width: `${battery}%` }}></div>
          </div>
        </section>
      </main>

      <footer className={styles.theoryBox}>
        <h3>Resumo Técnico: Inteligência & Layout</h3>
        <p>
          Este componente demonstra a fusão de <strong>Flexbox</strong> para alinhamento dinâmico e 
          <strong>Lógica Condicional JS</strong> integrada ao JSX. A interface "reage" ao estado <code>battery</code>: 
          ao atingir o limiar crítico, o React injeta dinamicamente classes de perigo, alterando a percepção visual do operador.
        </p>
      </footer>
    </div>
  );
};

export default Atividade05;

/* @section ArchitectureMap
 * Descrição técnica da estrutura e fluxo de dados.
 */

/*
 * RESUMO TEÓRICO
 * Alinhado com o Padrão de Entrega de Elite (Protocolo GEMINI).
 */
